### ISSUE TITLE
Correções de bugs para 1.0

### ISSUE THREAD

**Issue by boasfesta** [raijenki/elysium#6]
-  [x]  Spam de mensagem está absurdo, temos que remover logs de pacotes
  -  [X]  Remover caractere desconhecido em nova linha de quest
  -  [X]  Arrumar janela de Quests que um texto está sobrepondo outro (Aumentar a GUI)
 - [x] Aparentemente as Skills em área estão afetando NPCs de Quest (e talvez outros)
- [x] Pet não está nascendo ao logar
- [x] Descrições dos itens não estão sendo detalhadas

**Comment by raijenki** [comment]
Logs de pacotes removidos e só aparecem quando compilado no modo #DEBUG.
